### ISSUE TITLE
There's a grammatical error in the README so I stopped reading

### ISSUE THREAD

**Issue by adyotag** [dmadisetti/AirLatex.vim#18]
"It's a little like hacking yourself, and a nice reminder that any program you are run on your machine can do this and more. Here's [the relevant code](https://github.com/dmadisetti/AirLatex.vim/blob/main) if you are interested."

that and I want to spam an issue for attention lol

**Comment by dmadisetti** [comment]
Lol, why didn't a get a notification. Cloesd by 272d69f
