### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by firubat** [dmadisetti/AirLatex.vim#31]
After setting the Cookie manually, I run `AirLatex` , the splash screen and sidebar open but I get the following message in the sidebar:
```
Status: Offline. Error from 'https://www.overleaf.com'. Please Login. (are you logged in?)

```

Any help appreciated. I set the "debug mode" but doesn't seem it has any effect. I don't think any log file was created (at least I haven't found one).

**Comment by dmadisetti** [comment]
File should be called AirLatex.log in the directory you launched from.

```vim
let g:AirLatexLogLevel="DEBUG"
```

Can you share a censored version of your cookies? Should look like:

```vim
let g:AirLatexCookie = "cookies:overleaf_session2=s%3<string>.<string>"
```

If you tried the firefox approach, remove any variables associated, since this will supersede

**Comment by firubat** [comment]
OK found the log file. This is the error, it contains the censored cookie:

```
1730659835.5410542 | session / _checkLogin #71  : Finding Cookies
1730659835.5411 | session / _checkLogin #79  : Found Cookie for domain 'overleaf2_session' named 's%3********************.**************************'
1730659836.257484 | session / _buildProjectList #97  : https://www.overleaf.com/project
1730659836.257945 | session / _buildProjectList #108 : WebException: Couldn't find an element with name prefetchedProjectsBlob on the page.  b'<!DOCTYPE html><html lang="en"><head><title>Log in to Overleaf - Overleaf, Online LaTeX Editor</title><meta name="twitter:title" content="Log in to Overleaf"><meta name="og:title" content="Log in to Overleaf">.....
```
(I didn't copy the whole thing, seems it outputs the entire html the overleaf front page)

**Comment by firubat** [comment]
Another thing which I'm not sure if has anything to do with this - the time that appears with "Last update" on the side pane is not my local time.

**Comment by dmadisetti** [comment]
What version are you using? Are you using my branch?

**Comment by firubat** [comment]
it says version 0.2, I'm using `dmadisetti/AirLatex.vim`
Maybe I need to add something to the configuration? I'm using LazyVim (which uses lazy.nvim) and the config is simply 
```
return {
  "dmadisetti/AirLatex.vim",
  lazy = false,
}
```
(I ran `UpdateRemotePlugins` and I manually set the cookie)

**Comment by dmadisetti** [comment]
overleaf_session2 not overleaf2_session

My b. The readme is wrong

**Comment by dmadisetti** [comment]
Yeah, the update in in UTC. It hasn't really bothered me and came with the branch

**Comment by dmadisetti** [comment]
Lmk if that works

So actionables on my part (or contributors)
- fix readme
- fix bad login detection (although it sounds like it essentially worked)

**Comment by firubat** [comment]
Yes now it works! Awesome!
Such a silly mistake 😅 thanks for the help!



BTW, what controls which side is the sidepane located? I see on your demo that it's on the left while I have it on the right.


> Another thing which I'm not sure if has anything to do with this - the time that appears with "Last update" on the side pane is not my local time.

> Yeah, the update in in UTC. It hasn't really bothered me and came with the branch

It doesn't bother me as well, just mentioned it in case for some reason the time difference made things confused.

**Comment by dmadisetti** [comment]
I think AirLatexWinPos:

https://github.com/dmadisetti/AirLatex.vim/blob/1242b53b19d9a3d0e4694fa5e48136c6ef569563/rplugin/python3/airlatex/buffers/sidebar.py#L42
